import type { ContentPool } from "../types.ts";

// --- ContentPool — 可演化数据 ---

export function createDefaultContentPool(): ContentPool {
  return {
    needDefinitions: [
      {
        type: "hunger",
        baseUrgency: 0.5,
        decayRate: 5,
        description: "对食物的需求",
        bornFrom: "baseline",
      },
      {
        type: "safety",
        baseUrgency: 0.4,
        decayRate: 2,
        description: "对人身安全的需求",
        bornFrom: "baseline",
      },
      {
        type: "social",
        baseUrgency: 0.3,
        decayRate: 3,
        description: "对社交互动的需求",
        bornFrom: "baseline",
      },
      {
        type: "rest",
        baseUrgency: 0.2,
        decayRate: 8,
        description: "对休息的需求",
        bornFrom: "baseline",
      },
    ],

    actionEffects: [
      {
        action: "eat_at_tavern",
        needDeltas: { hunger: 30, social: 10 },
        itemCosts: { copper_coin: 3 },
        durationMinutes: 40,
      },
      { action: "eat_at_home", needDeltas: { hunger: 25 }, durationMinutes: 25 },
      { action: "sleep_at_home", needDeltas: { rest: 50 }, endsDay: true },
      {
        action: "work_at_smithy",
        needDeltas: { rest: -10 },
        itemDeltas: { iron_ore: 1 },
        durationMinutes: 120,
      },
      {
        action: "work_at_farm",
        needDeltas: { rest: -15, hunger: -5 },
        itemDeltas: { copper_coin: 2 },
        durationMinutes: 180,
      },
      { action: "guard_post", needDeltas: { safety: 10, rest: -5 }, durationMinutes: 180 },
      {
        action: "serve_lunch",
        needDeltas: { social: 10 },
        itemDeltas: { copper_coin: 2 },
        durationMinutes: 120,
      },
      {
        action: "serve_dinner",
        needDeltas: { social: 10 },
        itemDeltas: { copper_coin: 2 },
        durationMinutes: 120,
      },
      { action: "prepare_tavern", needDeltas: { rest: -5 }, durationMinutes: 120 },
      { action: "rest", needDeltas: { rest: 15 }, durationMinutes: 30 },
      {
        action: "tend_stall",
        needDeltas: { social: 5, rest: -8 },
        itemDeltas: { copper_coin: 3 },
        durationMinutes: 60,
      },
      { action: "count_coins", needDeltas: {}, durationMinutes: 10 },
      { action: "socialize", needDeltas: { social: 10 }, durationMinutes: 30 },
      { action: "patrol", needDeltas: { safety: 5, rest: -5 }, durationMinutes: 60 },
      { action: "move", needDeltas: { rest: -5 }, durationMinutes: 15 },
      { action: "talk", needDeltas: { social: 5, rest: -2 }, durationMinutes: 5 },
      { action: "say", needDeltas: { social: 5, rest: -1 }, durationMinutes: 3 },
      { action: "wait", needDeltas: { rest: 3 }, durationMinutes: 15 },
    ],

    needActionMap: [
      { needType: "hunger", actionNames: ["eat_at_tavern", "eat_at_home"] },
      { needType: "safety", actionNames: ["guard_post", "patrol"] },
      {
        needType: "social",
        actionNames: ["socialize", "eat_at_tavern", "serve_lunch", "serve_dinner", "tend_stall"],
      },
      { needType: "rest", actionNames: ["sleep_at_home", "rest"] },
    ],

    scheduleTemplates: [
      {
        role: "blacksmith",
        schedule: [
          {
            startHour: 6,
            endHour: 12,
            action: "work_at_smithy",
            targetRoomId: null,
            priority: 8,
            deviationAllowed: true,
          },
          {
            startHour: 12,
            endHour: 13,
            action: "eat_at_tavern",
            targetRoomId: null,
            priority: 9,
            deviationAllowed: false,
          },
          {
            startHour: 13,
            endHour: 18,
            action: "work_at_smithy",
            targetRoomId: null,
            priority: 8,
            deviationAllowed: true,
          },
          {
            startHour: 18,
            endHour: 19,
            action: "eat_at_tavern",
            targetRoomId: null,
            priority: 9,
            deviationAllowed: false,
          },
          {
            startHour: 19,
            endHour: 22,
            action: "socialize",
            targetRoomId: null,
            priority: 5,
            deviationAllowed: true,
          },
          {
            startHour: 22,
            endHour: 6,
            action: "sleep_at_home",
            targetRoomId: null,
            priority: 10,
            deviationAllowed: false,
          },
        ],
      },
      {
        role: "guard",
        schedule: [
          {
            startHour: 6,
            endHour: 14,
            action: "guard_post",
            targetRoomId: null,
            priority: 9,
            deviationAllowed: false,
          },
          {
            startHour: 14,
            endHour: 15,
            action: "eat_at_tavern",
            targetRoomId: null,
            priority: 9,
            deviationAllowed: false,
          },
          {
            startHour: 15,
            endHour: 22,
            action: "patrol",
            targetRoomId: null,
            priority: 8,
            deviationAllowed: true,
          },
          {
            startHour: 22,
            endHour: 6,
            action: "sleep_at_home",
            targetRoomId: null,
            priority: 10,
            deviationAllowed: false,
          },
        ],
      },
      {
        role: "farmer",
        schedule: [
          {
            startHour: 5,
            endHour: 12,
            action: "work_at_farm",
            targetRoomId: null,
            priority: 8,
            deviationAllowed: true,
          },
          {
            startHour: 12,
            endHour: 13,
            action: "eat_at_home",
            targetRoomId: null,
            priority: 9,
            deviationAllowed: false,
          },
          {
            startHour: 13,
            endHour: 18,
            action: "work_at_farm",
            targetRoomId: null,
            priority: 8,
            deviationAllowed: true,
          },
          {
            startHour: 18,
            endHour: 20,
            action: "eat_at_home",
            targetRoomId: null,
            priority: 9,
            deviationAllowed: false,
          },
          {
            startHour: 20,
            endHour: 5,
            action: "sleep_at_home",
            targetRoomId: null,
            priority: 10,
            deviationAllowed: false,
          },
        ],
      },
      {
        role: "tavern_keeper",
        schedule: [
          {
            startHour: 6,
            endHour: 12,
            action: "prepare_tavern",
            targetRoomId: null,
            priority: 9,
            deviationAllowed: false,
          },
          {
            startHour: 12,
            endHour: 14,
            action: "serve_lunch",
            targetRoomId: null,
            priority: 9,
            deviationAllowed: false,
          },
          {
            startHour: 14,
            endHour: 18,
            action: "rest",
            targetRoomId: null,
            priority: 7,
            deviationAllowed: true,
          },
          {
            startHour: 18,
            endHour: 23,
            action: "serve_dinner",
            targetRoomId: null,
            priority: 9,
            deviationAllowed: false,
          },
          {
            startHour: 23,
            endHour: 6,
            action: "sleep_at_home",
            targetRoomId: null,
            priority: 10,
            deviationAllowed: false,
          },
        ],
      },
      {
        role: "merchant",
        schedule: [
          {
            startHour: 7,
            endHour: 12,
            action: "tend_stall",
            targetRoomId: null,
            priority: 9,
            deviationAllowed: true,
          },
          {
            startHour: 12,
            endHour: 13,
            action: "eat_at_tavern",
            targetRoomId: null,
            priority: 8,
            deviationAllowed: false,
          },
          {
            startHour: 13,
            endHour: 18,
            action: "tend_stall",
            targetRoomId: null,
            priority: 9,
            deviationAllowed: true,
          },
          {
            startHour: 18,
            endHour: 19,
            action: "eat_at_home",
            targetRoomId: null,
            priority: 8,
            deviationAllowed: false,
          },
          {
            startHour: 19,
            endHour: 22,
            action: "count_coins",
            targetRoomId: null,
            priority: 6,
            deviationAllowed: true,
          },
          {
            startHour: 22,
            endHour: 7,
            action: "sleep_at_home",
            targetRoomId: null,
            priority: 10,
            deviationAllowed: false,
          },
        ],
      },
    ],

    narrativeTemplates: {
      eventTitles: {
        move: "移动",
        talk: "对话",
        wait: "等待",
        rest: "休息",
        look: "观察",
        take: "拾取",
        drop: "丢下",
        use: "使用",
        eat: "食用",
        read: "阅读",
        say: "说话",
        inventory: "背包",
        status: "状态",
        end_day: "结束今天",
        attack: "攻击",
        flee: "逃跑",
        defend: "防御",
        equip: "装备",
        unequip: "卸下",
        quests: "任务",
        trade: "交易",
        hostile: "敌对",
        help: "帮助",
        ignore: "无视",
        "entity.npc": "人物",
        "entity.item": "物品",
        "entity.player": "玩家",
        "entity.faction": "派系",
      },
      moveNarrative: "{actor} 到达了 {room}。",
      talkNarrative: '{actor}: "{query}"\n{target}: "{response}"',
      waitNarrative: "{actor} 在原地逗留了一会。",
      npcNotFound: "{npcName}不在这里。",
      npcSilentFallback: "{target}点了点头，没有多说什么。",
      emptyDaySummary: "平淡的一天。",
      moodLabels: [
        { threshold: 0, label: "低落" },
        { threshold: 50, label: "平静" },
        { threshold: 70, label: "愉快" },
      ],
      relationLabels: [
        { threshold: 0, label: "冷淡" },
        { threshold: 30, label: "普通" },
        { threshold: 50, label: "友好" },
      ],
      endingCommands: ["结束今天", "休息", "过完这天", "结束这一天"],
      chatPattern:
        "(和|跟|问|找|与)([^，。\\s]{1,6})(聊天|说话|讲话|打听|问话|聊聊|谈谈|对话|了解|问问)",
      directionNames: { 北: "north", 南: "south", 东: "east", 西: "west", 上: "up", 下: "down" },
      spectatorFallbackName: "旁观者",
      regionStatusLabels: {
        prosperityLow: "经济困难",
        threatHigh: "军事紧张",
        stable: "稳定",
      },
      defaultTheme: "边疆",
      memoryTemplates: {
        take: { self: "拿起了{item}", observer: "看到 {actor} 拿起了{item}" },
        drop: { self: "放下了{item}", observer: "看到 {actor} 放下了{item}" },
        move: {
          self: "到达了{room}",
          observerLeave: "看到 {actor} 离开了{room}",
          observerArrive: "{actor} 来到了{room}",
        },
        talk: {
          self: "与 {target} 在{room}交谈",
          target: "与 {actor} 在{room}交谈。{text}",
          observer: "注意到 {actor} 和 {target} 在{room}{action}",
          observerNoTarget: "注意到 {actor} 在{room}{action}",
        },
        look: { self: "{actor} 打量了我" },
        say: { observer: "听到 {actor} 在{room}说了话" },
        dailyRoutine: "度过了日常的一天",
        fallbackItemName: "东西",
      },
      combatTemplates: {
        attackStart: "{attacker} 对 {defender} 发起了攻击！",
        hit: "{attacker} 对 {defender} 造成了 {damage} 点伤害。",
        crit: "暴击！{attacker} 对 {defender} 造成了 {damage} 点伤害！",
        playerDown: "{target} 倒下了...",
        npcDefeated: "{target} 被击败了！",
        npcDeath: "{target} 死亡了。",
        npcFlee: "{actor} 逃跑了！",
        fleeSuccess: "{actor} 成功逃出了战斗！",
        fleeFail: "{actor} 试图逃跑，但被拦截了！",
        defend: "{actor} 摆出防御姿态，减少受到的伤害。",
      },
      commandMessages: {
        lookRoomTarget: "房间",
        lookRoom: "{room}: {description}。在场: {npcs}。物品: {items}。出口: {exits}",
        lookEntity: "观察 {target}。{details}",
        lookTargetNotFound: "没有看到 {target}。",
        take: "捡起了 {item}",
        drop: "放下了 {item}",
        useWithEffect: "使用了 {item}（{effect}）",
        useNoEffect: "使用了 {item}，暂时没有明显效果。",
        rest: "休息了一会，恢复了一些精力。",
        status: "状态: {needs}。",
        statusWithTraits: "状态: {needs}。特质: {traits}。",
        inventoryEmpty: "身上空无一物。",
        inventoryList: "携带物品: {items}",
        say: '{actor}: "{message}"',
        endDayRestItem: "你使用{item}休息，精力恢复 +{recovery}。",
        endDay: "{actor} {command}",
        equip: "装备了 {item}。",
        equipWithSwap: "装备了 {item}，卸下了 {previous}。",
        unequip: "卸下了 {item}。",
        eatWithEffect: "吃了 {item}（{effect}）",
        eatNoEffect: "吃了 {item}，暂时没有明显效果。",
        readWithEffect: "阅读了 {item}（{effect}）",
        readNoEffect: "阅读了 {item}。",
        readMissingContent: "{item} 标记为可阅读，但没有对应的书籍内容。",
        readNotReadable: "{item} 不可阅读",
        readSpecifyItem: "请指定要阅读的物品",
        readItemNotFound: "找不到要阅读的物品",
        roomAction: "{label}",
        roomActionWithEffect: "{label}（{effect}）",
      },
      settlementMessages: {
        dialogue: "{speaker}：{content}",
        relation: "结算 | 关系：{changes}",
        playerNeed: "结算 | 身体：{changes}",
        npcNeed: "结算 | 周围的人需求也发生了变化",
        item: "结算 | {entity}物品：{changes}",
      },
      questMessages: {
        completeTitle: "任务完成: {title}",
        completeDescription: "你完成了「{title}」。",
        failTitle: "任务失败: {title}",
        failDescription: "你未能在截止日期前完成「{title}」。",
        discoverTitle: "发现任务: {title}",
        discoverDescription: "你发现了「{title}」。",
        goodbyeOptionLabel: "告别",
        goodbyeNarrative: "{npcName}向你点头告别。",
        deferReply: "{npcName}点了点头，示意你可以之后再谈。",
        deferReplyFallback: "{npcName}点了点头。",
        acceptLabelTemplate: "我愿意接下「{questTitle}」。",
        deferLabel: "我先考虑一下。",
      },
      traveloguePrompt: `你是游记作家。请根据玩家今日的经历，以第三人称章回体小说的风格撰写一篇游记。

写作要求:
- 使用第三人称叙事，以角色名为叙述主语
- 章回体风格: 标题用简洁的章回名（如"第三回·苍山城初遇奇人"），正文要展现角色在世界的经历
- 3-5段正文，每段4-6句话，生动刻画场景
- 以地点为线索组织叙事，每到一个新地点另起一段
- 融入诗意描写：景色、氛围、角色的细微感受
- 保留遭遇NPC的对话要点

输出格式为严格的JSON:
{"title": "章回标题", "narrative": "正文内容"}`,
      conversationSummaryLabel: "此前对话概要",
      conversationSummaryPrompt: `你正在为一个 MUD 游戏生成 NPC 对话的简要总结。
根据以下对话历史，生成一句中文总结（不超过40字），概括这次对话的主要内容。
只需要返回总结文本，不要多余内容。

对话历史:
{history}`,
    },

    calendar: {
      hourStart: 6,
      daysPerMonth: 30,
      monthsPerYear: 12,
      monthNames: [
        "初春月",
        "仲春月",
        "暮春月",
        "初夏月",
        "仲夏月",
        "暮夏月",
        "初秋月",
        "仲秋月",
        "暮秋月",
        "初冬月",
        "仲冬月",
        "暮冬月",
      ],
      eraName: "铁器纪元",
      yearFormat: "{era}第{year}年",
      dayFormat: "第{day}日",
    },

    dayNightConfig: {
      periods: [
        { id: "dawn", startHour: 5, label: "清晨", visibilityModifier: 0.7 },
        { id: "morning", startHour: 7, label: "上午", visibilityModifier: 1.0 },
        { id: "afternoon", startHour: 12, label: "午后", visibilityModifier: 1.0 },
        { id: "dusk", startHour: 18, label: "黄昏", visibilityModifier: 0.8 },
        { id: "night", startHour: 21, label: "深夜", visibilityModifier: 0.5 },
      ],
    },

    seasonConfig: {
      seasons: [
        {
          id: "spring",
          name: "春",
          months: [1, 2, 3],
          label: "春",
          comfortTemp: 18,
          needDecayMultiplier: 1.0,
          narrativePrefix: "春风拂面",
        },
        {
          id: "summer",
          name: "夏",
          months: [4, 5, 6],
          label: "夏",
          comfortTemp: 32,
          needDecayMultiplier: 1.0,
          narrativePrefix: "烈日当空",
        },
        {
          id: "autumn",
          name: "秋",
          months: [7, 8, 9],
          label: "秋",
          comfortTemp: 15,
          needDecayMultiplier: 1.1,
          narrativePrefix: "秋风萧瑟",
        },
        {
          id: "winter",
          name: "冬",
          months: [10, 11, 12],
          label: "冬",
          comfortTemp: -8,
          needDecayMultiplier: 1.5,
          narrativePrefix: "寒风刺骨",
        },
      ],
    },

    weatherConfig: {
      weatherTypes: [
        {
          id: "clear",
          label: "晴朗",
          movementMultiplier: 1.0,
          visibilityMultiplier: 1.0,
          narrativeDesc: "阳光明媚",
          availableInSeasons: ["spring", "summer", "autumn", "winter"],
          weight: 50,
        },
        {
          id: "overcast",
          label: "阴天",
          movementMultiplier: 1.0,
          visibilityMultiplier: 0.9,
          narrativeDesc: "天空阴沉",
          availableInSeasons: ["spring", "summer", "autumn", "winter"],
          weight: 25,
        },
        {
          id: "light_rain",
          label: "细雨",
          movementMultiplier: 0.8,
          visibilityMultiplier: 0.7,
          narrativeDesc: "细雨蒙蒙",
          availableInSeasons: ["spring", "summer", "autumn"],
          weight: 15,
        },
        {
          id: "heavy_rain",
          label: "暴雨",
          movementMultiplier: 0.6,
          visibilityMultiplier: 0.5,
          narrativeDesc: "暴雨倾盆",
          availableInSeasons: ["summer", "autumn"],
          weight: 5,
        },
        {
          id: "fog",
          label: "大雾",
          movementMultiplier: 0.9,
          visibilityMultiplier: 0.4,
          narrativeDesc: "雾气弥漫",
          availableInSeasons: ["spring", "autumn"],
          weight: 10,
        },
        {
          id: "light_snow",
          label: "小雪",
          movementMultiplier: 0.7,
          visibilityMultiplier: 0.7,
          narrativeDesc: "雪花纷飞",
          availableInSeasons: ["winter"],
          weight: 15,
        },
        {
          id: "blizzard",
          label: "暴风雪",
          movementMultiplier: 0.4,
          visibilityMultiplier: 0.3,
          narrativeDesc: "风雪交加",
          availableInSeasons: ["winter"],
          weight: 5,
        },
      ],
    },

    warmthComfortConfig: {
      baselineTemp: 25,
      maxIdealWarmth: 30,
      minIdealWarmth: 0,
      penaltyPerWarmthPoint: 0.015,
    },

    behaviorAtoms: [],

    namePools: [
      {
        culture: "西境农耕文化",
        surnames: ["赵", "钱", "孙", "李", "周", "吴", "郑", "王", "冯", "陈"],
        maleGiven: ["行舟", "大山", "德", "仁", "勇", "守田", "铁柱", "志远", "青山", "福"],
        femaleGiven: ["秀", "兰", "春芽", "巧", "珠", "月", "翠", "芬", "桂英", "小荷"],
        neutralGiven: ["石头", "小河", "顺", "平安", "丰收"],
        epithetPatterns: ["老{char}", "{surname}铁匠", "{surname}{given}", "{role}{name}"],
      },
    ],

    roomTemplates: [
      {
        culture: "农耕",
        rooms: [
          { name: "小村庄", desc: "几间土坯房，烟囱冒着炊烟，鸡犬之声相闻。" },
          { name: "麦田", desc: "大片金黄的麦田，远处能看到几个农舍。" },
          { name: "河边磨坊", desc: "一座老旧的水车吱呀作响，几个村民在排队磨面。" },
          { name: "果园", desc: "桃树和李树成排，果子挂满枝头。" },
          { name: "猎人小屋", desc: "一座木屋，墙上挂着几张兽皮，门口晾着腊肉。" },
        ],
        names: ["赵大", "钱嫂", "孙老头", "李木匠", "周猎户"],
        personalities: ["勤劳朴实", "沉默寡言", "热情好客", "警惕陌生人", "爱讲故事"],
      },
      {
        culture: "军阀部落",
        rooms: [
          { name: "废弃营寨", desc: "木栅栏已经腐朽，但还能看到曾经驻军的痕迹。" },
          { name: "乱石岗", desc: "嶙峋的巨石间能藏不少人，有烧火留下的灰烬。" },
          { name: "哨塔废墟", desc: "一座半塌的石塔，视野开阔，能看到很远的距离。" },
        ],
        names: ["铁牙", "断臂老吴", "独眼狼"],
        personalities: ["粗鲁暴躁", "沉默戒惧", "亡命之徒", "讲义气"],
      },
    ],

    llmTriggerConfig: {
      worldEvent: { perSettlement: 1, enabled: true },
      memoryCompression: { maxCandidates: 3, minMemoriesToTrigger: 3, enabled: true },
      settlementGrowth: {
        npcToRoomRatio: 4,
        prosperityThreshold: 70,
        threatThreshold: 30,
        enabled: true,
      },
      contentPoolEvolve: { checkDay: 1, enabled: true },
      narrativeDirection: { intervalMonths: 1, enabled: false },
      culturalEvolution: { adoptionThreshold: 0.3, enabled: false },
      discoveryGeneration: { activityThreshold: 1000, enabled: false },
      dialogueOptions: { optionCount: 4, enabled: true },
    },

    // LLM tool_calls → 数值映射 (规则引擎查表, 不在 LLM 决定)
    dialogueEffectMapping: {
      relation: {
        slight_positive: { delta: 1 },
        moderate_positive: { delta: 2 },
        strong_positive: { delta: 4 },
        slight_negative: { delta: -1 },
        moderate_negative: { delta: -2 },
        strong_negative: { delta: -4 },
      },
      needImpact: {
        slight_positive: { delta: 3 },
        moderate_positive: { delta: 6 },
        strong_positive: { delta: 10 },
        slight_negative: { delta: -3 },
        moderate_negative: { delta: -6 },
        strong_negative: { delta: -10 },
      },
      information: {
        rumor: { memoryImportance: 0.3, spreadChance: 0.3 },
        warning: { memoryImportance: 0.5, spreadChance: 0.1 },
        gossip: { memoryImportance: 0.2, spreadChance: 0.5 },
        lore: { memoryImportance: 0.4, spreadChance: 0.1 },
        quest_hint: { memoryImportance: 0.6, spreadChance: 0 },
      },
      itemExchange: {
        trivial: { valueRange: [1, 3] },
        small: { valueRange: [3, 10] },
        moderate: { valueRange: [10, 30] },
      },
    },

    // 社会涟漪: 交互的社会信号 → 观察者评价 → 关系变化
    socialRippleConfig: {
      enabled: true,
      signalStrength: {
        talk: 2,
        trade: 1,
        hostile: -5,
        help: 4,
        ignore: -1,
        take: 1,
        use: 0,
      },
      // 关系权重: observer ↔ participant 的关系水平 → 放大系数
      // [-100, -50, -20, 20, 50, 100] 对应 [-2, -1, 0.3, 1, 1.5, 2]
      relationWeightPoints: [-100, -50, -20, 20, 50, 100],
      relationWeightMultipliers: [-2, -1, 0.3, 1, 1.5, 2],
      // 性格乘数 (1.0=中性, >1=放大, <1=缩小, 负=反转)
      traitMultipliers: {
        suspicious: 1.3,
        kind: 1.2,
        generous: 1.2,
        selfish: 0.4,
        pragmatic: 0.8,
        naive: 1.5,
        paranoid: 2.0,
        jealous: -1.5,
      },
      threshold: 0.5,
      maxDelta: 5,
    },

    emotionLabels: {
      grateful: "感激",
      angry: "愤怒",
      surprised: "惊讶",
      worried: "担忧",
      happy: "开心",
      disappointed: "失望",
      suspicious: "怀疑",
      amused: "觉得有趣",
      fearful: "恐惧",
      contemptuous: "轻蔑",
    },

    needLabels: {
      hunger: "饥饿",
      safety: "安全",
      social: "社交",
      rest: "精力",
      achievement: "成就",
    },

    traitLabels: {
      suspicious: "多疑",
      kind: "善良",
      generous: "慷慨",
      selfish: "自私",
      pragmatic: "务实",
      naive: "天真",
      paranoid: "偏执",
      jealous: "嫉妒",
      compassion: "同理心",
      trust: "信任",
      ambition: "野心",
      unity: "团结",
      greed: "贪婪",
      courage: "勇气",
      discipline: "自律",
      diligence: "勤奋",
      discontent: "不满",
      skepticism: "怀疑",
      optimism: "乐观",
    },

    sensitiveTraitNames: ["suspicious", "paranoid", "cautious", "jealous"],

    itemPropertyLabels: {
      currency: "货币",
      value: "价值",
      material: "材料",
      valuable: "贵重物",
      needDeltas: "效果",
      hungerRestore: "恢复饥饿",
      restRestore: "恢复精力",
      socialRestore: "恢复社交",
      safetyRestore: "恢复安全",
      restItem: "休息用品",
      restRecovery: "恢复精力",
      durability: "耐久",
      consumable: "消耗品",
      edible: "可食用",
      drinkable: "可饮用",
      usable: "可使用",
      lightSource: "光源",
      readable: "可阅读",
      spiritual: "灵性物品",
      weapon: "武器",
      atkBonus: "攻击",
      defBonus: "防御",
      questItem: "任务物品",
    },

    itemTemplates: [
      { id: "copper_coin", name: "铜币", properties: { currency: true } },
      { id: "iron_ore", name: "铁矿石", properties: { material: true } },
    ],

    bookContents: [],

    questTemplates: [],

    combatConfig: {
      baseHp: 50,
      enduranceToHp: 1.5,
      baseAtk: 5,
      skillToAtk: 0.4,
      strengthToAtk: 0.3,
      baseDef: 3,
      skillToDef: 0.2,
      enduranceToDef: 0.3,
      baseSpd: 5,
      skillToSpd: 0.2,
      agilityToSpd: 0.3,
      damageMultiplier: 1.0,
      defenseReductionPerPoint: 0.6,
      minDamage: 1,
      damageVariance: 0.2,
      critBaseChance: 0.1,
      critSpdBonus: 0.002,
      critMultiplier: 1.5,
      pulseInterval: 3,
      restCostPerAttack: 1,
      fleeBaseChance: 0.5,
      fleeSpdBonus: 0.015,
      incapacitatedDuration: 120,
      defendingBonus: 5,
      defenseDamageMultiplier: 0.5,
      npcHostilityThreshold: -30,
      npcAttackCooldown: 60,
      fleeHpThreshold: 0.3,
      fleeCourageThreshold: 0,
      fleeBaseAttemptChance: 0.3,
      defaultCourageValue: 50,
    },
    combatSkills: [],

    storylineConfig: { eventLookbackWindow: 10 },

    terrainConfig: [],

    entityActionsByTag: {},
    entityActionLabels: {},
    entityTagLabels: {},

    conversationDirections: [],
    clueDefinitions: [],
  };
}
